### ISSUE TITLE
Usability improvements for goconserver as we prepare to package with xCAT 2.13.11 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/goconserver#26]
Without much documentation , I am giving the `goconserver` a try and seeing what I can figure out from a usability perspective.   Will edit/add to this issue as I find more... 

1. Any reason why we choose `congo` instead of `gocons` as the command name? 
2. Message when conserver or goconserver is running can be better

   When conserver is running, and trying to execute `makegocons`, the following message comes out: 

   ```
   [root@stratton01 ~]# makegocons 
   Error: conserver is started, please stop it at first.
   ```

   Suggest something like: 
   ```
   [root@stratton01 ~]# makegocons
   Error: conserver is running, did you mean 'makeconservercf'? If not, stop conserver and retry.
   ```

   The reverse:
   ```
   [root@fs2vm110 ~]# makeconservercf f6u17
   Error: goconserver is started, please stop it at first.
   ```

   Suggest something like: 
   ```
   [root@fs2vm110 ~]# makeconservercf f6u17
   Error: goconserver is running, did you mean `makegocon'? If not, stop goconserver and retry.
   ```

   This may help those who have muscle memory and typing the wrong command.  Also would help those who are un-aware the admin switched to goconserver, and trying to run `makeconservercf` on a console before running `rcons`. 

3. `congo list` doesn't seem to work 
   ```
   [root@fs2vm112 ~]# congo list
   Could not list resources, Get http://127.0.0.1:12429/nodes: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
   [root@fs2vm112 ~]#
   ```
4. Other congo commands have a similar problem
   ```
   [root@fs2vm111 gurevich]# congo create testnode driver=ssh ondemand=false --params user=root,host=10.6.7.254,port=22,password=xxxxx
   Post http://127.0.0.1:12429/nodes: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"
   ```
   ```
   [root@fs2vm111 gurevich]# congo create testnode driver=cmd ondemand=false --params cmd="ssh -l root -p 22 10.6.7.254"
   Post http://127.0.0.1:12429/nodes: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"
   [root@fs2vm111 gurevich]#
   ```
5. Why do we create a new server.conf file https://github.com/xcat2/xcat-core/blob/master/xCAT-server/lib/perl/xCAT/Goconserver.pm#L524.   Wouldn't it be better to sed the values instead of creating a static file.  If goconserver ships a newer version of the server.conf file, it will revert back to this version hard coded in xcat-core...

**Comment by chenglch** [comment]
@whowutwut ,
1. Not too much reasons, when I start `goconserver` work， I don't know how to choose a name for it, at that time `goconserver` is not its name. For `congo`, I just think it's a `console` with `golang`.
2. This seems reasonable, I will change it based on your comments in `xCAT-core` repo.
3. `congo` can be looked as  a internal command for xCAT user, as `makegocons` and `rcons` are wrapper for it. As you have already run the `makegocons` command from xCAT, the `/etc/goconserver/server.conf` has been changed (from http mode to https mode with certification of xCAT), you must specify the environment variable for it, for example
```
[root@briggs01 ~]# cat /etc/profile.d/congo.sh
export CONGO_URL="https://briggs01:12429"
export CONGO_SERVER_HOST="briggs01"
export CONGO_PORT="12430"
export CONGO_CONSOLE_TIMEOUT=3
export CONGO_SSL_KEY=/root/.xcat/client-key.pem
export CONGO_SSL_CERT=/root/.xcat/client-cred.pem
export CONGO_SSL_CA_CERT=/root/.xcat/ca.pem
export CONGO_SSL_INSECURE=false
``` 
`rcons` would not affect by this environment variables, it could be run directly after `makegocons`. 
4. Same as 3 above
5. Yes, it's a problem , I attempt to add a new option `-c|--conf <conf_file>`  for `makegocons` command, but it seems hard due to the `noderange` design of xCAT.

**Comment by whowutwut** [comment]
@jjohnson42 Let's wait for @chenglch to get back from the holiday to respond to this.  I did bring up the possibility of using confluent and I don't recall the reason why that was not taken and @chenglch wrote this in Go. 

One requirement we had was to write console output to TCP port, but that probably could have been done in confluent...

**Comment by jjohnson42** [comment]
That's fine, just was being surprised.

Our security team would not be happy with us offering a plain TCP port anyway, so that could have been awkward on my end to try to explain.
