### ISSUE TITLE
goconserver license

### ISSUE THREAD

**Issue by mattaezell** [xcat2/goconserver#60]
Is goconserver licensed under the EPL like xCAT?  Could a licensing statement be added to the codebase?

**Comment by besawn** [comment]
Yes, goconserver is licensed under the EPL like xCAT. We will investigate adding a licensing statement to make this more explicit.

**Comment by jabl** [comment]
Considering EPL-1.0 has been superseded by EPL-2.0, and that EPL in general is not particularly widely used and even where it is, it's mostly for Java projects, have you considered adopting some more common license, such as Apache-2.0?

**Comment by besawn** [comment]
@jabl Sorry for the delay - when xCAT was originally open sourced, EPL-1.0 was the most appropriate license for the project at the time. Do the licensing terms of EPL-1.0 cause any specific challenges for you when using xCAT?

**Comment by jabl** [comment]
Nothing in particular, just that EPL-2.0 was evidently made in order to fix deficiencies in EPL-1.0. So if you're splatting on a new license, might as well take the latest version, no?

Personally, I'm happy with copyleft licensing, and I think file-level weak copyleft licenses like EPL or MPL2 are a nice compromise between "do whatever you want" and "give improvements back". It just unfortunately seems the mere mention of copyleft causes rashes for some, but that's a different discussion I guess.

Hypothetically speaking, if I were to ask the legal dept. at $WORK for permission to contribute to xcat, I would guess the bigger hurdle would be the copyright assignment requirement rather than which particular OSS license you use..

**Comment by gurevichmark** [comment]
License added with #62

**Comment by besawn** [comment]
@jabl Thanks for the feedback, we have no plans to change the license terms at this time, but we will keep this in mind as an item for future consideration.
